apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: tf-zookeeper-operator
  namespace: contrail
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - tf-zookeeper-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - zookeeper.tungstenfabric.io
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tf-zookeeper-operator
  namespace: contrail
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tf-zookeeper-operator
  namespace: contrail
subjects:
- kind: ServiceAccount
  name: tf-zookeeper-operator
  namespace: contrail
roleRef:
  kind: Role
  name: tf-zookeeper-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: zookeepers.zookeeper.tungstenfabric.io
spec:
  group: zookeeper.tungstenfabric.io
  names:
    kind: Zookeeper
    listKind: ZookeeperList
    plural: zookeepers
    singular: zookeeper
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          type: object
        status:
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tf-zookeeper-operator
  namespace: contrail
spec:
  replicas: 1
  selector:
    matchLabels:
      name: tf-zookeeper-operator
  template:
    metadata:
      labels:
        name: tf-zookeeper-operator
    spec:
      nodeSelector:
          node-role.kubernetes.io/master: ''
      tolerations:
      - operator: Exists
        effect: NoSchedule
      - operator: Exists
        effect: NoExecute
      hostNetwork: true
      serviceAccountName: tf-zookeeper-operator
      containers:
        - name: tf-zookeeper-operator
          # Replace this with the built image name
          image: docker.io/michaelhenkel/zookeeper-tf-operator:v0.0.1
          command:
          - tf-zookeeper-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "tf-zookeeper-operator"
---
apiVersion: zookeeper.tungstenfabric.io/v1alpha1
kind: Zookeeper
metadata:
  name: zookeeper
  namespace: contrail
spec:
  # Add fields here
  size: 3
  hostnetwork: true
  registry: docker.io/michaelhenkel
  version: 5.1.1-dev
